name: smart_gh
description: An Smart Approach for Smart Farming

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  animated_splash_screen: ^1.2.0
  curved_navigation_bar: ^1.0.3
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/splash.png

  uses-material-design: true

